-- Create likes table if not exists
CREATE TABLE IF NOT EXISTS public.likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users NOT NULL,
    liked_user_id UUID REFERENCES auth.users NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(user_id, liked_user_id)
);

-- Create matches table if not exists
CREATE TABLE IF NOT EXISTS public.matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_a UUID REFERENCES auth.users NOT NULL,
    user_b UUID REFERENCES auth.users NOT NULL,
    matched_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CHECK (user_a < user_b),
    UNIQUE(user_a, user_b)
);

-- Create function to handle reciprocal likes
CREATE OR REPLACE FUNCTION public.handle_like()
RETURNS TRIGGER AS $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM public.likes
        WHERE user_id = NEW.liked_user_id
        AND liked_user_id = NEW.user_id
    ) THEN
        INSERT INTO public.matches (user_a, user_b)
        VALUES (
            LEAST(NEW.user_id, NEW.liked_user_id),
            GREATEST(NEW.user_id, NEW.liked_user_id)
        )
        ON CONFLICT (user_a, user_b) DO NOTHING;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger for new likes
CREATE TRIGGER on_like_created
AFTER INSERT ON public.likes
FOR EACH ROW
EXECUTE FUNCTION public.handle_like();